export const featuredToursData = [
  {
    id: '12-jyotirlinga-tour-package',
    title: '12 Jyotirlinga Tour Package',
    description:
      '12 Jyotirlinga Tour Package takes the pilgrims to the 12 pious temples of Lord Shiva collectively called 12 Jyotirlinga or Dwadash Jyotirlinga.',
    duration: { nights: 17, days: 18 },
    price: '0',
    rating: 5,
    best_time: 'Oct–Mar',
    ideal_for: 'Pilgrims/Devotees, Families, Seniors',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/12-jyotirlinga-tour-package/12-Jyotirlinga-Tour-Package5.jpg',
    ],
    cities: [
      { name: 'Dwarka', label: 'Dwarka' },
      { name: 'Guptkashi', label: 'Guptkashi' },
      { name: 'Haridwar', label: 'Haridwar' },
      { name: 'Kedarnath', label: 'Kedarnath' },
      { name: 'Omkareshwar', label: 'Omkareshwar' },
    ],
    themes: [{ id: '12-jyotirlinga-tour', name: '12 Jyotirlinga Tour' }],
  },
  {
    id: '5-days-rajasthan-tour-package',
    title: '5 Days Rajasthan Tour Package',
    description:
      'Explore Rajasthan in short time with 5 days Rajasthan tour package. Visit Amber Fort, Pushkar Lake, City Palace, Brahma Temple.',
    duration: { nights: 4, days: 5 },
    price: '0',
    rating: 5,
    best_time: 'Oct–Mar',
    ideal_for: 'Culture/History Lovers, Families, Couples, Seniors, Photographers',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/5-days-rajasthan-tour-package/5-Days-Rajasthan-Tour-Package5.jpg',
    ],
    cities: [
      { name: 'Jaipur', label: 'Jaipur' },
      { name: 'Mount Abu', label: 'Mount Abu' },
      { name: 'Pushkar', label: 'Pushkar' },
      { name: 'Udaipur', label: 'Udaipur' },
    ],
    themes: [{ id: 'rajasthan-tours', name: 'Rajasthan Tours' }],
  },
  {
    id: 'agra-fatehpur-sikri-tour',
    title: 'Agra Fatehpur Sikri Tour',
    description:
      'Agra Fatehpur Sikri tour takes travellers from Delhi to the historical destinations of Agra and Fatehpur Sikri.',
    duration: { nights: 0, days: 1 },
    price: '0',
    rating: 5,
    best_time: 'Oct–Mar or Year-round with heat precautions',
    ideal_for: 'Families, Couples, Seniors, Culture/History Lovers, Photographers',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-fatehpur-sikri-tour/Agra-Fatehpur-Sikri-Tour5.jpg',
    ],
    cities: [
      { name: 'Agra', label: 'Agra' },
      { name: 'Delhi', label: 'Delhi' },
      { name: 'Fatehpur Sikri', label: 'Fatehpur Sikri' },
    ],
    themes: [
      { id: 'weekend-tours', name: 'Weekend Tours' },
      { id: 'taj-mahal-tours', name: 'Taj Mahal Tours' },
    ],
  },
  {
    id: 'agra-jaipur-tour',
    title: 'Agra Jaipur Tour',
    description:
      'Agra Jaipur Tour is designed to take travellers to two of the most visited tourist cities of India - Agra and Jaipur.',
    duration: { nights: 1, days: 2 },
    price: '0',
    rating: 3,
    best_time: 'Oct–Mar',
    ideal_for: 'Culture/History Lovers, Families, Couples, Seniors, Photographers',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-jaipur-tour/Agra-Jaipur-Tour5.jpg',
    ],
    cities: [
      { name: 'Agra', label: 'Agra' },
      { name: 'Delhi', label: 'Delhi' },
      { name: 'Jaipur', label: 'Jaipur' },
    ],
    themes: [
      { id: 'weekend-tours', name: 'Weekend Tours' },
      { id: 'taj-mahal-tours', name: 'Taj Mahal Tours' },
    ],
  },
  {
    id: 'agra-mathura-vrindavan-tour-from-delhi',
    title: 'Agra Mathura Vrindavan Tour from Delhi',
    description:
      'Book your Agra Mathura Vrindavan Tour from Delhi. Visit Temples of Mathura & Vrindavan. Also visit Taj Mahal and Red Fort in Agra.',
    duration: { nights: 3, days: 4 },
    price: '0',
    rating: 3,
    best_time: 'Oct–Mar or Year-round with heat precautions',
    ideal_for: 'Families, Couples, Seniors, Culture/History Lovers, Photographers',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-mathura-vrindavan-tour-from-delhi/Agra-Mathura-Vrindavan-Tour-from-Delhi5.jpg',
    ],
    cities: [
      { name: 'Agra', label: 'Agra' },
      { name: 'Delhi', label: 'Delhi' },
      { name: 'Mathura', label: 'Mathura' },
      { name: 'Vrindavan', label: 'Vrindavan' },
    ],
    themes: [{ id: 'uttar-pradesh-tours', name: 'Uttar Pradesh Tours' }],
  },
  {
    id: 'agra-overnight-tour',
    title: 'Agra Overnight Tour',
    description:
      'Explore Agra in 2 days with the Agra Overnight Tour. Visit the heritage sites in Agra like Agra Fort, Sikandra Fort, Red Fort besides the Taj Mahal.',
    duration: { nights: 1, days: 2 },
    price: '0',
    rating: 3,
    best_time: 'Oct–Mar or Year-round with heat precautions',
    ideal_for: 'Families, Couples, Seniors, Culture/History Lovers, Photographers',
    imageUrls: [
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour1.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour2.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour3.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour4.jpg',
      'https://dbagut2mvh0lo.cloudfront.net/tours/agra-overnight-tour/Agra-Overnight-Tour5.jpg',
    ],
    cities: [{ name: 'Agra', label: 'Agra' }],
    themes: [
      { id: 'weekend-tours', name: 'Weekend Tours' },
      { id: 'taj-mahal-tours', name: 'Taj Mahal Tours' },
      { id: 'cultural-tour', name: 'Cultural Tour' },
    ],
  },
];
